# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test & Publish

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore \
        -p:Version=$Version \
        -p:PackageVersion=$NuGetPackageVersion \
        -p:AssemblyVersion=$AssemblyVersion \
        -p:FileVersion=$Version \
        -p:AssemblyFileVersion=$AssemblyFileVersion \
        -p:AssemblyInformationalVersion=$AssemblyInformationalVersion \
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: pack
      run: dotnet pack --include-symbols --include-source -o packages
    - name: upload packages
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: packages/*
    - name: Hello world action
      env: # Or as an environment variable
        super_secret: ${{ secrets.NUGET_KEY }}
      run: echo $super_secret
    #- name: push to NuGet
     # run: dotnet nuget push --api-key
